wdl-ast/CHANGELOG.md
wdl-ast/src/v1/document/expression.rs
wdl-ast/src/v1/document/workflow/execution/statement/call/body.rs

This commit fixes the incorrect filter when iterating over the pairs provided to the `parse` function for `Expression`.
Fixes #21.
good, articulated reason as to why there shouldn be more than one).

fix: ignore comments when parsing `Expression`.

---

Gauntlet.toml
RULES.md
wdl-core/src/concern/lint/group.rs
wdl-grammar/CHANGELOG.md
wdl-grammar/src/v1.rs
wdl-grammar/src/v1/lint.rs
wdl-grammar/src/v1/lint/newline_eof.rs

This pull request adds a new rule to `wdl`.
- **Rule Name**: `newline_eof`
- **Rule Kind**: Lint warning
- **Rule Code**: `v1::W007`
- **Packages**: `wdl-grammar`
This rule is currently written as to avoid missing newline at the end of WDL files.
My interpretation of the rule is that a WDL file should not end with an empty line (double newline symbols), but the rule description is not explicit about that (or the opposite situation). 
The implementation currently checks two things :
- there is at least one newline at the end of the file
- there is at most one newline at the end of file
Let me know if this implementation is not suitable
good, articulated reason as to why there shouldn be more than one). …

feat: add lint warning for newline_eof

---

Cargo.toml
wdl-grammar/CHANGELOG.md
wdl-grammar/Cargo.toml
wdl-grammar/src/experimental.rs
wdl-grammar/src/experimental/lexer.rs
wdl-grammar/src/experimental/lexer/v1.rs
wdl-grammar/src/lib.rs

This commit introduces an `experimental` module as a placeholder for a new parser implementation, feature-gated by the `experimental` feature.
To start, a lexer implementation based on `logos` has been added.
The lexer may have several different token types depending on context, mainly to support interpolation in string literals and commands.
The implementation should be enough to lex a 1.x WDL document.
The parser implementation that will make use of the lexer is forthcoming.
good, articulated reason as to why there shouldn't be more than one).

feat: implement a WDL lexer using `logos`.

---

.github/pull_request_template.md
wdl-grammar/CHANGELOG.md
wdl-grammar/src/experimental/grammar.rs
wdl-grammar/src/experimental/grammar/v1.rs
wdl-grammar/src/experimental/lexer.rs
wdl-grammar/src/experimental/parser.rs
wdl-grammar/src/experimental/tree.rs
wdl-grammar/tests/parsing/missing-version/source.tree
wdl-grammar/tests/parsing/struct-definitions/source.tree
wdl-grammar/tests/parsing/struct-definitions/source.wdl
wdl-grammar/tests/parsing/struct-recovery/source.errors
wdl-grammar/tests/parsing/struct-recovery/source.tree
wdl-grammar/tests/parsing/struct-recovery/source.wdl
wdl-grammar/tests/parsing/top-recovery/source.errors
wdl-grammar/tests/parsing/top-recovery/source.tree
wdl-grammar/tests/parsing/top-recovery/source.wdl
wdl-grammar/tests/parsing/unsupported-version/source.tree
wdl-grammar/tests/parsing/valid-version/source.tree

This commit implements the parsing of WDL struct definitions in the experimental parser.
The `experimental` feature is still required to use the new parser.
good, articulated reason as to why there should be more than one).

feat: implement parsing of struct definitions in experimental parser.

---

wdl-grammar/CHANGELOG.md
wdl-grammar/src/experimental/grammar/v1.rs
wdl-grammar/src/experimental/lexer.rs
wdl-grammar/src/experimental/parser.rs
wdl-grammar/tests/parsing/interpolation/source.tree
wdl-grammar/tests/parsing/interpolation/source.wdl

This commit fixes the parsing of placeholder options by adding a `peek2` method to check for an assignment token following the option identifier.
Without the assignment token present, it should treat the contents as an expression, such as a call to the `sep` function.
Currently `Lexer::peek` is retokenizing on every `peek` followed by `next`; a forthcoming PR will properly cache the result of `peek` so that re-tokenization will only ever occur for `peek2`, which will only be called for string placeholders.
good, articulated reason as to why there should be more than one). …

fix: fix placeholder option parsing in the experimental parser.

---

wdl-grammar/CHANGELOG.md
wdl-grammar/src/experimental/grammar/v1.rs
wdl-grammar/src/experimental/lexer/v1.rs
wdl-grammar/src/experimental/parser.rs
wdl-grammar/src/experimental/tree.rs
wdl-grammar/tests/parsing/command-sections/source.tree
wdl-grammar/tests/parsing/command-sections/source.wdl
wdl-grammar/tests/parsing/escaped-newlines/source.tree
wdl-grammar/tests/parsing/escaped-newlines/source.wdl

This commit implements parsing of command sections in tasks for the
experimental parser.
good, articulated reason as to why there should be more than one).

feat: implement parsing command sections in the experimental parser. 

---

.github/pull_request_template.md
.github/workflows/CI.yml
Arena.toml
wdl-gauntlet/CHANGELOG.md
wdl-gauntlet/Cargo.toml
wdl-gauntlet/src/config.rs
wdl-gauntlet/src/config/reportable_concern.rs
wdl-gauntlet/src/lib.rs
wdl-gauntlet/src/repository.rs
wdl-gauntlet/src/repository/work_dir.rs

**The goal of `THE ARENA` is to ensure new lints produce sane warnings for WDL "in the wild".**
New `--arena` flag for `wdl-gauntlet` that ignores all syntax errors (`ParseError` or `ValidationFailure`) and instead just reports `LintWarning`. This comes with it's own config file, `Arena.toml`.
Arena has been seeded with 3 repos and their warnings, but that's probably worth revisiting. My process for these 3 was simple elimination starting from `Gauntlet.toml`. I ran `--arena` on each of those 13 repos and excluded anything that returned an overwhelming number of Warnings. That was 10 of the 13 😬 .
While testing out arena on some of the test repos I've already logged issues (#50) with existing warnings.
["keep a …

feat(wdl-gauntlet): ENTER THE ARENA

---

wdl-grammar/CHANGELOG.md
wdl-grammar/src/experimental/grammar/v1.rs
wdl-grammar/tests/parsing/struct-definitions/source.tree
wdl-grammar/tests/parsing/struct-definitions/source.wdl

This commit fixes the experimental parser to access a postfix `+` qualifier on array types.

fix: accept postfix `+` qualifier in array types.

---

wdl-grammar/CHANGELOG.md
wdl-grammar/src/experimental/grammar/v1.rs
wdl-grammar/src/experimental/parser.rs
wdl-grammar/tests/parsing/empty-call/source.tree
wdl-grammar/tests/parsing/empty-call/source.wdl
wdl-grammar/tests/parsing/mismatched-brace/source.errors
wdl-grammar/tests/parsing/mismatched-bracket/source.errors
wdl-grammar/tests/parsing/unterminated-metadata-string/source.errors

This commit fixes the experimental parser to allow for empty braces following a task call expression.
Additionally, it refactors the "matched" token utility functions and the expected error variants.

fix: fix empty call inputs.

---

wdl-grammar/CHANGELOG.md
wdl-grammar/src/experimental/grammar/v1.rs
wdl-grammar/tests/parsing/interpolation/source.tree
wdl-grammar/tests/parsing/multiple-placeholder-opts/source.tree
wdl-grammar/tests/parsing/multiple-placeholder-opts/source.wdl

This commit changes the experimental parser to accept multiple placeholder options instead of just one.
We will later validate during a validation pass that there is at most one placeholder option specified, but we should accept multiple options in the grammar.

fix: accept multiple placeholder options in experimental parser.

---

wdl-grammar/CHANGELOG.md
wdl-grammar/src/experimental/grammar/v1.rs
wdl-grammar/src/experimental/lexer/v1.rs
wdl-grammar/src/experimental/tree.rs
wdl-grammar/tests/parsing/atoms/source.tree
wdl-grammar/tests/parsing/atoms/source.wdl

This commit treats `None` as a literal `None` value in expressions, rather than a name reference; this distinguishes `None` as a special value.

fix: treat `None` as a literal expression in the experimental parser.

---

wdl-grammar/CHANGELOG.md
wdl-grammar/src/experimental/grammar.rs
wdl-grammar/src/experimental/lexer.rs
wdl-grammar/src/experimental/parser.rs
wdl-grammar/src/experimental/tree.rs
wdl-grammar/tests/parsing/missing-version/source.tree
wdl-grammar/tests/parsing/unsupported-version/source.errors
wdl-grammar/tests/parsing/unsupported-version/source.tree
wdl-grammar/tests/parsing/unsupported-version/source.wdl

This commit fixes the experimental parser such that it will skip the remaining source if it encounters a missing or unsupported WDL version.
Now it emits a single error and adds a special "unparsed" token representing the remainder of the file.

fix: skip remaining source for unsupported versions.

---

Arena.toml
RULES.md
wdl-grammar/CHANGELOG.md
wdl-grammar/src/v1.rs
wdl-grammar/src/v1/lint.rs
wdl-grammar/src/v1/lint/double_quotes.rs

This pull request adds a new rule to `wdl`.
- **Rule Name**: `double_quotes`
- **Rule Kind**: Lint warning
- **Rule Code**: `v1::W012`
- **Packages**: `wdl-grammar`
Warns about strings defined with single-quotes. This ignores anything located inside the command section. Tests are not exhaustive, there are quite a lot of things that are using strings. Should they still be added?
good, articulated reason as to why there should be more than one).
tables (`wdl-ast/src/v1.rs` for AST-based rules and 
`wdl-grammar/src/v1.rs` for parse tree-based rules).
table at `RULES.md`.
- Validation rules added to `wdl-ast` should be added to `fn rules()` within 
`wdl-ast/src/v1/validation.rs`.
- …

feat: double_quotes

---

wdl-lint/src/v1.rs
wdl-lint/src/v1/no_curly_commands.rs
wdl-lint/tests/lints/curly-command/source.errors
wdl-lint/tests/lints/curly-command/source.wdl

feat: NoCurlyCommands rule

---

wdl-ast/CHANGELOG.md
wdl-ast/src/experimental.rs
wdl-ast/src/experimental/v1.rs
wdl-ast/src/experimental/v1/decls.rs
wdl-ast/src/experimental/v1/expr.rs
wdl-ast/src/experimental/v1/import.rs
wdl-ast/src/experimental/v1/struct.rs
wdl-ast/src/experimental/v1/task.rs
wdl-ast/src/experimental/v1/validation/counts.rs
wdl-ast/src/experimental/v1/validation/numbers.rs
wdl-ast/src/experimental/v1/visitor.rs
wdl-ast/src/experimental/v1/workflow.rs
wdl-lint/CHANGELOG.md
wdl-lint/Cargo.toml
wdl-lint/src/v1/ending_newline.rs
wdl-lint/src/v1/no_curly_commands.rs

This commit adds a `parent` method to the AST representation of sections.
For task-specific sections, the method returns `TaskDefinition`.
For sections that appear in both tasks and workflows, the method returns a `TaskOrWorkflow` enumeration.
Also included is removing `rowan` as a dependency of `wdl-lint` by re-exporting what's needed from `wdl-ast`.

feat: add `parent` method to AST sections.

---

wdl-ast/src/experimental/v1/decls.rs
wdl-lint/CHANGELOG.md
wdl-lint/src/v1.rs
wdl-lint/src/v1/matching_parameter_meta.rs
wdl-lint/tests/lints/matching-param-meta/source.errors
wdl-lint/tests/lints/matching-param-meta/source.wdl
wdl-lint/tests/lints/snake-case/source.errors
wdl-lint/tests/lints/snake-case/source.wdl

This commit ports the "matching parameter meta" rule to `wdl-lint`.

feat: port the `MatchingParameterMeta` rule to `wdl-lint`.

---

Cargo.toml
wdl-ast/CHANGELOG.md
wdl-ast/Cargo.toml
wdl-gauntlet/CHANGELOG.md
wdl-gauntlet/Cargo.toml
wdl-gauntlet/src/lib.rs
wdl-grammar/CHANGELOG.md
wdl-grammar/Cargo.toml
wdl-lint/CHANGELOG.md
wdl-lint/Cargo.toml
wdl/CHANGELOG.md
wdl/Cargo.toml

This bumps all of the crate versions to 0.4.0.
It also removes the dependency from gauntlet to `wdl-ast` as it can just use the re-export via `wdl-lint`.

chore: bump crate versions to 0.4.0.

---

Cargo.toml
wdl-ast/CHANGELOG.md
wdl-ast/Cargo.toml
wdl-gauntlet/CHANGELOG.md
wdl-gauntlet/Cargo.toml
wdl-grammar/CHANGELOG.md
wdl-grammar/Cargo.toml
wdl-lint/CHANGELOG.md
wdl-lint/Cargo.toml
wdl/CHANGELOG.md
wdl/Cargo.toml

This reverts commit db706639b24633b1903e9a3ed4934d4434af3400.
I'm working on an automation to determine if a crate needs to be released and to have it automatically bump the versions and do so in accordance with the existing documented release process.
In the meantime, revert the previous PR (we're not releasing today anyway as we're blocked on publishing `wdl-lint`).

revert: bump crate versions to 0.4.0 (db70663).

---

wdl-grammar/CHANGELOG.md
wdl-grammar/src/parser.rs
wdl-grammar/tests/parsing/missing-comma/source.errors
wdl-grammar/tests/parsing/missing-comma/source.tree
wdl-grammar/tests/parsing/missing-comma/source.wdl

This commit changes the `delimited` method of `Parser` to add a label to the expected diagnostic for a missing delimiter.
It does this by finding the last non-trivia token event and using its span to point at where the missing delimiter might go.
Also fixes a failure to consume a delimiter if recovery stops at a delimiter.
Fixes #67.

fix: add a label for suggesting where to put a missing delimiter.

---

Gauntlet.toml
wdl-grammar/CHANGELOG.md
wdl-grammar/src/diagnostic.rs
wdl-grammar/src/grammar/v1.rs
wdl-grammar/src/lexer/v1.rs
wdl-grammar/src/parser.rs
wdl-grammar/tests/parsing/recovery-past-string/source.errors
wdl-grammar/tests/parsing/unexpected-string/source.errors
wdl-grammar/tests/parsing/unexpected-string/source.tree
wdl-grammar/tests/parsing/unexpected-string/source.wdl

This fix improves any diagnostic that has a label pointing at a string.
Previously the label would point just at the opening quote of the string because we don't know the span of the string until after we recover; recovery asks the lexer to move past any interpolations it encounters.
The fix is to pass the diagnostic we're recovering for to the `recover` method and adjust any labels that start an interpolation context to include the source that was moved past.
Fixes #80.

fix: improve diagnostics that have a label pointing at a string.

---

Arena.toml
wdl-ast/src/lib.rs
wdl-grammar/CHANGELOG.md
wdl-grammar/src/grammar/v1.rs
wdl-grammar/src/parser.rs
wdl-grammar/tests/parsing/imports/source.tree
wdl-grammar/tests/parsing/missing-version/source.tree
wdl-lint/CHANGELOG.md
wdl-lint/RULES.md
wdl-lint/src/v1.rs
wdl-lint/src/v1/import_placement.rs
wdl-lint/src/v1/preamble_whitespace.rs
wdl-lint/tests/lints/import-placements/source.errors
wdl-lint/tests/lints/import-placements/source.wdl
wdl-lint/tests/lints/missing-blank-line-after-version/source.errors
wdl-lint/tests/lints/missing-blank-line-after-version/source.wdl

**Rule Name**: `ImportPlacement`
This commit implements the `ImportPlacement` rule which warns if an import comes after a non-import top-level item in the document.
Additionally, this fixes the `PreambleWhitespace` rule to check for a blank line following the version statement.
Also fixed:
* Last whitespace in the file was attaching as a child to the last node in the document instead of as top-level whitespace.
* The CST for an "unparsed" file (i.e. missing version statement or unsupported version) was missing trivia before the version statement and the unparsed token span was incorrect.
possible diagnostic emitted for the rule within the file where the rule   …

feat: implement the `ImportPlacement` rule.

---

Arena.toml
Gauntlet.toml
wdl-lint/CHANGELOG.md
wdl-lint/RULES.md
wdl-lint/src/v1.rs
wdl-lint/src/v1/pascal_case.rs
wdl-lint/src/v1/snake_case.rs
wdl-lint/tests/lints/pascal-case/source.errors
wdl-lint/tests/lints/pascal-case/source.wdl

- **Rule Name**: `PascalCase`
Ensures that struct names use pascal case.
possible diagnostic emitted for the rule within the file where the rule  

feat: implement the `PascalCase` rule.

---

wdl-gauntlet/src/lib.rs
wdl-lint/CHANGELOG.md
wdl-lint/Cargo.toml
wdl-lint/src/except.rs
wdl-lint/src/lib.rs
wdl-lint/src/rules/preamble_comments.rs
wdl-lint/tests/lints.rs
wdl-lint/tests/lints/command-mixed-line-cont/source.errors
wdl-lint/tests/lints/command-mixed-line-cont/source.wdl
wdl-lint/tests/lints/command-mixed-spaces-first/source.errors
wdl-lint/tests/lints/command-mixed-spaces-first/source.wdl
wdl-lint/tests/lints/command-mixed-tabs-first/source.errors
wdl-lint/tests/lints/command-mixed-tabs-first/source.wdl
wdl-lint/tests/lints/command-mixed-trailing/source.errors
wdl-lint/tests/lints/command-mixed-trailing/source.wdl
wdl-lint/tests/lints/command-mixed-ws-ok/source.errors
wdl-lint/tests/lints/command-mixed-ws-ok/source.wdl
wdl-lint/tests/lints/command-mixed/source.errors
wdl-lint/tests/lints/command-mixed/source.wdl
wdl-lint/tests/lints/double-quotes/source.wdl
wdl-lint/tests/lints/except/source.errors
wdl-lint/tests/lints/except/source.wdl
wdl-lint/tests/lints/one-invalid-preamble-comment/source.errors
wdl-lint/tests/lints/one-invalid-preamble-comment/source.wdl
wdl-lint/tests/lints/pascal-case/source.wdl
wdl-lint/tests/lints/snake-case/source.wdl
wdl/src/bin/wdl.rs

This commit implements support for `#@ except` comments for linting.
If the comment appears in the preamble, the rule will be disabled for the entire document.
Otherwise, if the comment precedes a node in the AST, the rule will be disabled for that node and all of its children.

feat: implement support for `#@ except` comments in `wdl-lint`.

---

wdl-gauntlet/src/lib.rs
wdl-lint/CHANGELOG.md
wdl-lint/src/lib.rs
wdl-lint/src/rules/command_mixed_indentation.rs
wdl-lint/src/rules/double_quotes.rs
wdl-lint/src/rules/ending_newline.rs
wdl-lint/src/rules/import_placement.rs
wdl-lint/src/rules/import_sort.rs
wdl-lint/src/rules/import_whitespace.rs
wdl-lint/src/rules/inconsistent_newlines.rs
wdl-lint/src/rules/input_not_sorted.rs
wdl-lint/src/rules/line_width.rs
wdl-lint/src/rules/matching_parameter_meta.rs
wdl-lint/src/rules/missing_metas.rs
wdl-lint/src/rules/missing_output.rs
wdl-lint/src/rules/missing_runtime.rs
wdl-lint/src/rules/no_curly_commands.rs
wdl-lint/src/rules/pascal_case.rs
wdl-lint/src/rules/preamble_comments.rs
wdl-lint/src/rules/preamble_whitespace.rs
wdl-lint/src/rules/snake_case.rs
wdl-lint/src/rules/whitespace.rs
wdl-lint/src/visitor.rs
wdl-lint/tests/lints.rs
wdl/src/bin/wdl.rs
wdl/src/lib.rs

Originally, `Visitor` was version specific, so the idea was that you would ask a rule for its "V1" visitor, "V2" visitor, etc. to add to the validator.
However, that is no longer the case as `Visitor` is now version agnostic.
Therefore, this commit removes the unnecessary "visitor" types implementing the rules by having `Rule` be a supertrait of `Visitor`; now the rules themselves implement the `Visitor` trait.
I also renamed `ExceptVisitor` to simply `LintVisitor` to make the API a little cleaner; the visitor now means "run all lint rules and respect `except` comments". The name `ExceptVisitor` was too specific. …

refactor: make `Rule` a supertrait of `Visitor`.

---

.github/pull_request_template.md
Arena.toml
Gauntlet.toml
wdl-lint/CHANGELOG.md
wdl-lint/RULES.md
wdl-lint/src/lib.rs
wdl-lint/src/rules.rs
wdl-lint/src/rules/deprecated_object.rs
wdl-lint/src/tags.rs
wdl-lint/tests/lints/deprecated-object/source.errors
wdl-lint/tests/lints/deprecated-object/source.wdl
wdl-lint/tests/lints/input-not-sorted/source.errors
wdl-lint/tests/lints/input-not-sorted/source.wdl

- **Rule Name**: `DeprecatedObject`
This rule is part of the [baseline ruleset](https://github.com/stjude-rust-labs/wdl/discussions/11). Note that this should be merged in after #109, as I based the branch on that to avoid commit hash diffs showing up.
possible diagnostic emitted for the rule within the file where the rule   …

feat: implements the `deprecated_object` lint rule

---

wdl-ast/CHANGELOG.md
wdl-ast/src/lib.rs
wdl-ast/src/v1/expr.rs
wdl-ast/src/validation.rs
wdl-ast/src/validation/version.rs
wdl-ast/tests/validation/exponentiation-unsupported/source.errors
wdl-ast/tests/validation/exponentiation-unsupported/source.wdl
wdl-grammar/CHANGELOG.md
wdl-grammar/src/grammar.rs
wdl-grammar/src/grammar/v1.rs
wdl-grammar/src/lexer/v1.rs
wdl-grammar/src/tree.rs
wdl-grammar/tests/parsing/exponentiation/source.tree
wdl-grammar/tests/parsing/exponentiation/source.wdl
wdl-grammar/tests/parsing/precedence/source.tree
wdl-grammar/tests/parsing/precedence/source.wdl

This commit implements initial support for WDL 1.2 with the introduction of the exponentiation operator.
This is only initial support for 1.2; there are a number of changes required for the parser to be 1.2 spec-compliant and for the lint rules to be updated.

feat: add initial support for 1.2 with the exponentiation operator.

---

wdl-analysis/src/scope.rs
wdl-ast/CHANGELOG.md
wdl-ast/src/v1/expr.rs
wdl-ast/src/v1/task.rs
wdl-ast/src/v1/workflow.rs
wdl-ast/src/validation.rs
wdl-ast/src/validation/exprs.rs
wdl-ast/src/validation/keys.rs
wdl-ast/src/validation/version.rs
wdl-ast/src/visitor.rs
wdl-ast/tests/validation/hints-duplicate-keys/source.errors
wdl-ast/tests/validation/hints-duplicate-keys/source.wdl
wdl-ast/tests/validation/hints-unsupported/source.errors
wdl-ast/tests/validation/hints-unsupported/source.wdl
wdl-ast/tests/validation/hints/source.wdl
wdl-ast/tests/validation/scoped-exprs/source.errors
wdl-ast/tests/validation/scoped-exprs/source.wdl
wdl-grammar/CHANGELOG.md
wdl-grammar/src/grammar.rs
wdl-grammar/src/grammar/v1.rs
wdl-grammar/src/tree.rs
wdl-grammar/tests/parsing/hints-section/source.tree
wdl-grammar/tests/parsing/hints-section/source.wdl
wdl-lint/src/visitor.rs

This commit implements `hints` sections from WDL 1.2.
Unlike `runtime` sections, a `hints` section also introduces three scoped types: `hints`, `input`, and `output`; each of these have matching literal expressions which can only be used in the context of a `hints` section.
Additionally, this commit introduces the restriction of reserved names on tasks, workflows, import aliases, call aliases, structs, and struct aliases.
Reserved names are still allowed as struct members and input and output items and also in name reference expressions.

feat: implement `hints` sections from WDL 1.2.

---

wdl-ast/CHANGELOG.md
wdl-ast/src/v1/expr.rs
wdl-ast/src/validation/strings.rs
wdl-ast/src/validation/version.rs
wdl-ast/tests/validation/multiline-strings-unsupported/source.errors
wdl-ast/tests/validation/multiline-strings-unsupported/source.wdl
wdl-ast/tests/validation/multiline-strings/source.wdl
wdl-grammar/CHANGELOG.md
wdl-grammar/src/grammar/v1.rs
wdl-grammar/src/lexer/v1.rs
wdl-grammar/src/parser.rs
wdl-grammar/tests/parsing/metadata/source.tree
wdl-grammar/tests/parsing/metadata/source.wdl
wdl-grammar/tests/parsing/multiline-strings/source.tree
wdl-grammar/tests/parsing/multiline-strings/source.wdl
wdl-grammar/tests/parsing/recovery-past-string/source.errors
wdl-grammar/tests/parsing/recovery-past-string/source.tree
wdl-grammar/tests/parsing/recovery-past-string/source.wdl
wdl-lint/src/rules/double_quotes.rs

This commit implements support for multi-line strings that borrows from the
heredoc command syntax.

feat: implement multi-line strings from WDL 1.2. 

---

wdl-ast/CHANGELOG.md
wdl-ast/src/validation/version.rs
wdl-ast/tests/validation/missing-call-input-unsupported/source.errors
wdl-ast/tests/validation/missing-call-input-unsupported/source.wdl
wdl-ast/tests/validation/missing-call-input/source.wdl
wdl-grammar/CHANGELOG.md
wdl-grammar/src/grammar/v1.rs
wdl-grammar/tests/parsing/optional-call-input/source.tree
wdl-grammar/tests/parsing/optional-call-input/source.wdl

This commit implements optionally accepting `input` keywords in call statement
bodies in WDL 1.2.

feat: implement optional input keyword in call statements for WDL 1.2. 

---

Arena.toml
wdl-lint/CHANGELOG.md
wdl-lint/RULES.md
wdl-lint/src/lib.rs
wdl-lint/src/rules.rs
wdl-lint/src/rules/todo.rs
wdl-lint/tests/lints/todo/source.errors
wdl-lint/tests/lints/todo/source.wdl

- **Rule Name**: `TodoRule`
This rule flags `TODO` items with a note so that they are never forgotten. 
This is not part of the baseline ruleset (to my knowledge at least), so it may be worth some discussion as to whether this is desired. I tend to think so though.
possible diagnostic emitted for the rule within the file where the rule …

feat: implements a rule to flag `TODO` items

---

wdl-ast/CHANGELOG.md
wdl-ast/src/lib.rs
wdl-ast/src/validation/keys.rs
wdl-ast/src/visitor.rs
wdl-lint/src/rules/runtime_section_keys.rs

This removes the restriction on `Visitor` to be `Send` and `Sync`.
Originally the restriction was put in place in the hopes that they would be needed to implement `wdl-analysis`; however, that turned out to not be the case.
The restriction prevents visitors from storing AST elements as they are not `Send` (only green nodes and tokens are `Send` and `Sync`).
Thus, rules would previously have to clone token string representations if they were needed.
With these changes comes a `TokenStrHash` helper that can be used to hash an AST token by its string representation; a few rules were updated to use it to prevent unnecessary string clones.
Fixes #122. …

fix: remove the `Send` and `Sync` requirement on `Visitor`.

---

Arena.toml
wdl-lint/CHANGELOG.md
wdl-lint/src/rules/section_order.rs

Also allow hints sections
Fixes the SectionOrder rule so that it doesn't fire on every `WorkflowItem::Conditional`. While I was at it I tweaked the language of `explanation()` and permitted `hints` sections.

fix(SectionOrder): allow workflow conditionals

---

Arena.toml
Gauntlet.toml
wdl-lint/src/rules/line_width.rs
wdl-lint/tests/lints/line-width/source.errors
wdl-lint/tests/lints/line-width/source.wdl

In attempting to fix the `line_width` rule, I discovered that the problem was actually in the way we did excepting of rules. That's probably a PR for a different day, but I made some improvements to the rule in terms of conciseness that I'd like to go ahead and merge in.

revise: makes various improvements to the `line_width` rule

---

wdl/CHANGELOG.md
wdl/Cargo.toml
wdl/src/lib.rs

This PR promotes the `wdl-analysis` crate to be available under the `wdl` crate at `wdl::analysis`. This allows `wdl-analysis` to be used externally (albeit with the pre-v1 conditions).
cc: @peterhuene 

feat: promotes `wdl-analysis` to `wdl::analysis`

---

Arena.toml
Gauntlet.toml
wdl-ast/src/v1/task.rs
wdl-ast/src/validation.rs
wdl-ast/src/visitor.rs
wdl-lint/CHANGELOG.md
wdl-lint/RULES.md
wdl-lint/src/lib.rs
wdl-lint/src/rules.rs
wdl-lint/src/rules/trailing_comma.rs
wdl-lint/src/visitor.rs
wdl-lint/tests/lints/comment-whitespace/source.wdl
wdl-lint/tests/lints/input-spacing/source.wdl
wdl-lint/tests/lints/matching-param-meta/source.wdl
wdl-lint/tests/lints/nonmatching-output/source.wdl
wdl-lint/tests/lints/struct-matching-param-meta/source.errors
wdl-lint/tests/lints/struct-matching-param-meta/source.wdl
wdl-lint/tests/lints/trailing-comma/source.errors
wdl-lint/tests/lints/trailing-comma/source.wdl

- **Rule Name**: `TrailingComma`
This rule enforces that the last item in a MetadataObject or MetadataArray has a trailing comma. This only applies if there is > 1 child.
possible diagnostic emitted for the rule within the file where the rule
overridden that callback method for the special `Validator`
(`wdl-ast/src/validation.rs`) and `LintVisitor`
(`wdl-lint/src/visitor.rs`) visitors. These are required to ensure the new
visitor callback will execute.

feat: trailing comma lint rule

---

wdl-lint/CHANGELOG.md
wdl-lint/src/visitor.rs

Currently `LintVisitor` will remove rules from the rule set upon document entry when there's a "global" exception.
This works for a single document visit, but if the visitor is reused, the subsequent visitation will treat any previously globally excepted rules as unknown rules.
The fix is to use the `each_enabled_rule` for the `document` method so that globally excepted rules behave like locally excepted rules and the rule set doesn't change.
Fixes #145.

fix: allow reuse for `LintVisitor`.

---

wdl-ast/CHANGELOG.md
wdl-ast/src/v1/decls.rs
wdl-ast/src/v1/expr.rs
wdl-ast/src/v1/task.rs
wdl-ast/src/v1/task/common/container/value.rs
wdl-ast/src/v1/task/requirements/item/container.rs
wdl-ast/src/v1/task/runtime/item/container.rs
wdl-ast/src/v1/workflow.rs
wdl-lint/src/rules/matching_parameter_meta.rs
wdl-lint/src/rules/missing_metas.rs
wdl-lint/src/rules/missing_output.rs
wdl-lint/src/rules/missing_requirements.rs
wdl-lint/src/rules/missing_runtime.rs
wdl/examples/explore.rs

This commit refactors both `TaskDefinition` and `WorkflowDefinition` in the AST to return `Option<T>` for the section methods rather than iterator.
Therefore, only the first section in the AST is returned.
If multiple sections are present, validation will still flag the duplicate sections as errors.
Fixes #149.

refactor: change section methods to return `Option<T>`.

---

Gauntlet.toml
wdl-ast/CHANGELOG.md
wdl-ast/src/v1/expr.rs
wdl-ast/src/validation/strings.rs
wdl-ast/tests/validation/duplicate-placeholder-options/source.errors
wdl-ast/tests/validation/duplicate-placeholder-options/source.wdl
wdl-lint/src/rules/deprecated_placeholder_option.rs

This commit adds a check to the validation rules for ensuring there is at most one placeholder option in a placeholder.
Consequently, the `options` method on `Placeholder` has been renamed to `option` and now returns `Option<PlaceholderOption>`.
Fixes #154.

fix: validate placeholder options.

---

Cargo.toml
README.md
wdl-analysis/CHANGELOG.md
wdl-analysis/Cargo.toml
wdl-analysis/src/lib.rs
wdl-analysis/src/scope.rs
wdl-analysis/src/stdlib.rs
wdl-analysis/src/stdlib/constraints.rs
wdl-analysis/src/types.rs

This commit implements the basis for a type checking implementation in `wdl-analysis`.
It includes:
* a type system representation.
* a type coercion implementation.
* a definition of stdlib function signatures.
* function type parameter inference
* binding argument types to a function signature to determine a return type.
* function overload resolution.
This will all be used in the near future to implement full type checking in `wdl-analysis`.

feat: implement the basis for type checking in `wdl-analysis`.

---

wdl-analysis/CHANGELOG.md
wdl-analysis/src/scope.rs
wdl-analysis/src/scope/v1.rs
wdl-analysis/src/stdlib.rs
wdl-analysis/src/types.rs
wdl-analysis/tests/analysis/recursive-structs/foo.wdl
wdl-analysis/tests/analysis/recursive-structs/source.diagnostics
wdl-analysis/tests/analysis/recursive-structs/source.wdl
wdl-analysis/tests/analysis/unknown-type/foo.wdl
wdl-analysis/tests/analysis/unknown-type/source.diagnostics
wdl-analysis/tests/analysis/unknown-type/source.wdl

This commit implements type checking on struct definitions.
To accomplish this, a dependency graph is built for locally defined structs and cycles are detected and a diagnostic is emitted for recursively defined structs.
Otherwise, the type is calculated for the struct, which is done in topological order to resolve type name references.
This includes a refactor to move code related to a V1 AST out of `scope.rs` and into `scope/v1.rs`.
Also fixed a bug in the signature of `write_json` in the standard library: it should return `File` and not `Union`. …

feat: type check struct definitions.

---

wdl-ast/src/v1/expr.rs
wdl-ast/tests/validation/scoped-exprs/source.wdl
wdl-grammar/CHANGELOG.md
wdl-grammar/src/grammar/v1.rs
wdl-grammar/tests/parsing/hints-section/source.tree
wdl-grammar/tests/parsing/hints-section/source.wdl

This commit adds required commas to delineate items in `input`, `output`, and `hints` literals.
These literals are modeled after literal objects and literal structs, which have comma delimiters with an optional trailing comma.
This was missed as the spec only has one example of more than one item in these literals (introduced in 1.2), but that example does have a comma.

fix: require commas for `input`, `output`, and `hints` literals.

---

wdl-analysis/CHANGELOG.md
wdl-analysis/src/scope.rs
wdl-analysis/src/scope/v1.rs
wdl-analysis/src/stdlib.rs
wdl-analysis/src/stdlib/constraints.rs
wdl-analysis/src/types.rs
wdl-analysis/src/types/v1.rs
wdl-analysis/tests/analysis/task-variable-unsupported/source.diagnostics
wdl-analysis/tests/analysis/task-variable-unsupported/source.wdl
wdl-analysis/tests/analysis/task-variable/source.diagnostics
wdl-analysis/tests/analysis/task-variable/source.wdl

This commit introduces support for the `task` variable in type checking for WDL 1.2 documents.
It resolves the `task` variable to type `Task`, which has a well-known list of members and their types.
This partially completes #164.

feat: introduce support for the `task` variable from WDL 1.2.

---

Cargo.toml
wdl-analysis/CHANGELOG.md
wdl-analysis/Cargo.toml
wdl-analysis/src/graph.rs
wdl-analysis/src/queue.rs
wdl-gauntlet/CHANGELOG.md
wdl-gauntlet/Cargo.toml
wdl-gauntlet/src/config.rs
wdl-gauntlet/src/lib.rs
wdl-gauntlet/src/main.rs
wdl-gauntlet/src/repository.rs
wdl-lint/CHANGELOG.md
wdl-lint/src/util.rs
wdl-lsp/CHANGELOG.md
wdl-lsp/Cargo.toml
wdl-lsp/src/proto.rs
wdl-lsp/src/server.rs
wdl/CHANGELOG.md
wdl/Cargo.toml
wdl/src/bin/wdl.rs

This PR replaces all uses of the `log` crate with the same functionality from `tracing` events. In most spots this means we just replace `log::info!`/`debug!`/`error!` with `tracing`'s versions of these macros. 
It removes the need to use `if log_enabled!(...) { ... }` as `tracing` automatically does this, and requires us to use `tracing-subscriber` instead of `env_logger` for configuring a log filter. 
Closes #150 

feat: Replace all Log instances with Tracing events

---

wdl-analysis/src/scope/v1.rs
wdl-ast/CHANGELOG.md
wdl-ast/src/v1/task.rs
wdl-ast/src/v1/workflow.rs
wdl-ast/src/validation.rs
wdl-ast/src/validation/exprs.rs
wdl-ast/src/validation/keys.rs
wdl-ast/src/validation/version.rs
wdl-ast/src/visitor.rs
wdl-ast/tests/validation/hints-unsupported/source.wdl
wdl-ast/tests/validation/hints/source.wdl
wdl-grammar/CHANGELOG.md
wdl-grammar/src/grammar/v1.rs
wdl-grammar/src/tree.rs
wdl-grammar/tests/parsing/hints-section/source.tree
wdl-grammar/tests/parsing/hints-section/source.wdl
wdl-lint/src/rules/blank_lines_between_elements.rs
wdl-lint/src/visitor.rs

This commit fixes the parsing of workflow `hints` sections such that the values in the `hints` sections are always literals (no expressions supported).
To fix this, we need to parse the `workflow` hints section much like a metadata section where expressions aren't supported.
It required splitting out the previous `HintsSection` AST representation into two types: `TaskHintsSection` and `WorkflowHintsSection`, where the items in the former support expressions for values and the latter does not.
Fixes #169.

fix: parse workspace `hints` sections such that expressions are not supported.

---

Arena.toml
wdl-lint/CHANGELOG.md
wdl-lint/src/rules/whitespace.rs
wdl-lint/tests/lints/between-import-whitespace/source.errors
wdl-lint/tests/lints/blank-lines-between-elements/source.errors
wdl-lint/tests/lints/one-line-after-version/source.wdl
wdl-lint/tests/lints/only-whitespace/source.errors
wdl-lint/tests/lints/trailing-comment-whitespace/source.errors
wdl-lint/tests/lints/trailing-comment-whitespace/source.wdl

This PR adds a new check to the `Whitespace` linting rule that checks for trailing whitespace in all types of comments. It is tested against preamble comments, linting directives and normal comments to ensure this behavior. 
Issue: [174](https://github.com/stjude-rust-labs/wdl/issues/174)
possible diagnostic emitted for the rule within the file where the rule
overridden that callback method for the special `Validator`
(`wdl-ast/src/validation.rs`) and `LintVisitor`
(`wdl-lint/src/visitor.rs`) visitors. These are required to ensure the new
visitor callback will execute.~
unintended changes to the baseline …

feat: Trailing Comment Whitespace Lint

---

.github/workflows/bump.yml
.github/workflows/release.yml
ci/Cargo.toml
ci/src/main.rs

Part 2 of the new release process!
When there's a tag matching`wdl-v*` pushed to `main`, this kicks off publishing to crates.io and creating a GitHub release. The GitHub release will have auto-generated release notes based on the merged PRs since the last release. Example [here](https://github.com/stjude-rust-labs/wdl/releases/tag/untagged-db7e6b7505c9a55fa426)
This also features a change to the previous `bump` step where CHANGELOGS are now updated as well.

ci: release

---

.github/workflows/release.yml

The CI on `main` has turned red: https://github.com/stjude-rust-labs/wdl/actions/workflows/release.yml
The `Release` action should only run if there's a matching tag, but it currently runs on all `main` pushes.

fix: CI on main

---

Gauntlet.toml
wdl-analysis/CHANGELOG.md
wdl-analysis/src/diagnostics.rs
wdl-analysis/src/stdlib.rs
wdl-analysis/src/stdlib/constraints.rs
wdl-analysis/src/types/v1.rs
wdl-analysis/tests/analysis/common-types/source.wdl
wdl-analysis/tests/analysis/type-mismatch/source.diagnostics

* Realize return values of generic functions without constraints if we've failed to bind a function to the arguments; this will help determine the return types of functions like `select_first` and `select_any` when there are argument type mismatches.
* Allow `Union` to bind to generic `Pair`, `Map`, and `Array` as `Pair[Union, Union]`, `Map[Union, Union]`, and `Array[Union]`, respectively.
* Fix common type calculations for `if` expressions, `Array` literals, and `Map` literals.
Fixes #208.

fix: improve analysis type checks.

---

wdl-lsp/CHANGELOG.md
wdl-lsp/src/proto.rs

This commit adds the fix from a `Diagnostic` to the LSP representation (as an additional related information).
Fixes #192.

fix: add fixes to LSP diagnostics.

---

Gauntlet.toml
wdl-analysis/CHANGELOG.md
wdl-analysis/src/diagnostics.rs
wdl-analysis/src/scope/v1.rs
wdl-analysis/src/types.rs
wdl-analysis/src/types/v1.rs
wdl-analysis/tests/analysis/non-empty-array/source.diagnostics
wdl-analysis/tests/analysis/non-empty-array/source.wdl
wdl-analysis/tests/analysis/type-mismatch/source.diagnostics
wdl-ast/src/v1/expr.rs

This commit allows coercions of `Array[T]` to `Array[T]+` unless the assignment
is from an empty array literal, which can be easily statically checked.
Fixes #212.

fix: accept Array[T] to Array[T]+ coercions.

---

Cargo.toml
ci/src/main.rs
wdl-analysis/src/scope.rs
wdl-analysis/src/stdlib.rs
wdl-analysis/src/stdlib/constraints.rs
wdl-analysis/src/types.rs
wdl-analysis/src/types/v1.rs
wdl-ast/src/lib.rs
wdl-ast/src/v1.rs
wdl-ast/src/v1/decls.rs
wdl-ast/src/v1/expr.rs
wdl-ast/src/v1/struct.rs
wdl-ast/src/v1/task.rs
wdl-ast/src/v1/workflow.rs
wdl-engine/CHANGELOG.md
wdl-engine/Cargo.toml
wdl-engine/src/lib.rs
wdl-engine/src/value.rs
wdl-grammar/src/lexer.rs
wdl-lint/src/tags.rs
wdl/Cargo.toml
wdl/src/lib.rs

This PR introduces a `wdl-engine` crate that will eventually be responsible for implementing a WDL execution engine.
Currently the crate only defines two important types: `Engine` and `Value`.
`Engine` will be used to evaluate WDL source files, but is currently limited to instantiating values.
`Value` represents a runtime WDL value; currently it implements the coercion rules and a `display` method to format the value.
The next step is for `Engine` to analyze a WDL document and proceed to evaluation if there are no diagnostics.
Once that is implemented, support for the WDL JSON format will be added as a way to pass input values into the evaluation. …

feat: add a `wdl-engine` crate.

---

wdl-format/CHANGELOG.md
wdl-format/src/v1/expr.rs
wdl-format/tests/format/multiline-strings/source.formatted.wdl
wdl-format/tests/format/multiline-strings/source.wdl

Adds the `OpenHeredoc` and `CloseHeredoc` tokens to acceptable child tokens of string literals.

fix: fix panic in `wdl-format` when formatting 1.2 multiline strings.

---

Cargo.toml
ci/Cargo.toml
ci/src/main.rs
wdl-analysis/CHANGELOG.md

This commit enables the `rustls-tls` feature for the `reqwest` feature of `wdl-analysis`.
This should eliminate the OpenSSL dependency for Linux builds.

chore: use rustls-tls for `reqwest` dependency.

---

.github/workflows/CI.yml
wdl-analysis/tests/analysis.rs
wdl-format/tests/format.rs
wdl-lint/tests/lints.rs
wdl-lsp/CHANGELOG.md
wdl-lsp/src/server.rs

This fixes LSP requests that contain percent encoded colons and
lowercase drive letters in request URIs.
This caused the analyzer to report an empty set of diagnostics on Windows because
the requested document was unknown to the analyzer (it uses both a colon
and an uppercase drive letter in the document graph).
The fix is to percent decode the path segments and normalize the drive
letter to uppercase in the LSP server.
Fixes https://github.com/stjude-rust-labs/wdl/issues/229.

fix: normalize LSP request URIs.

---

Gauntlet.toml
README.md
wdl-analysis/CHANGELOG.md
wdl-analysis/src/analyzer.rs
wdl-analysis/src/diagnostics.rs
wdl-analysis/src/document.rs
wdl-analysis/src/document/v1.rs
wdl-analysis/src/eval/v1.rs
wdl-analysis/src/graph.rs
wdl-analysis/src/lib.rs
wdl-analysis/src/queue.rs
wdl-analysis/src/types.rs
wdl-analysis/src/types/v1.rs
wdl-grammar/src/diagnostic.rs
wdl/Cargo.toml
wdl/src/bin/wdl.rs

This PR refactors the analysis API to assist in future engine work.
Primarily it exposes `Task` and `Workflow` from analyzed documents so that a task or workflow's inputs and outputs can be easily determined.
Additionally, this renames `DocumentScope` to simply `Document` to represent an analyzed document.
Scopes are now kept internally to a `Task` or `Workflow`, which allows for a `scope` method directly on those types.
As a result of the rename, `scope.rs` has been renamed to `document.rs`.

refactor: refactor the analysis API.

---

wdl-analysis/CHANGELOG.md
wdl-analysis/src/diagnostics.rs
wdl-analysis/src/document.rs
wdl-analysis/src/document/v1.rs
wdl-analysis/src/stdlib/constraints.rs
wdl-analysis/src/types.rs
wdl-analysis/src/types/v1.rs
wdl-analysis/tests/analysis/call-unknown-input/source.diagnostics

This commit refactors `CallOutputType` to `CallType` so that the call can represent both the calls inputs and outputs in the type information.
Additionally, workflows now expose a map of call names to call types.
This allows the analyzed document to describe the calls a workflow makes so that nested inputs can be validated.
Also fixes a bug where the local call name was being used in diagnostics instead of the original task or workflow name.

refactor: refactor call types in `wdl-analysis`.

---

.gitattributes
.github/workflows/CI.yml
gauntlet/src/document/identifier.rs
gauntlet/src/repository.rs
wdl-lint/src/rules/line_width.rs

We should make sure `wdl` is always tested to work on all major platforms. To that end, I've updated the CI here to ensure that it always is. Some steps don't need to be run multi-platform, others clearly do, and then there are a few that are in-between (e.g., linting).
In both the "definitely needs to be run on all platforms" and the "in-between" ones, I ended up just enabling multi-platform tests to be safe. For example, for linting, some lints may only show up when certain platform-based configuration options are available. This is only going to become more relevant as we add more platform-specific things (like the encoding of newlines for UNIX/Windows).
[conventional …

ci: makes relevant CI tests multi-platform

---

Arena.toml
Cargo.toml
Gauntlet.toml
gauntlet/src/lib.rs
wdl-analysis/CHANGELOG.md
wdl-analysis/src/diagnostics.rs
wdl-analysis/src/document.rs
wdl-analysis/src/document/v1.rs
wdl-analysis/src/lib.rs
wdl-analysis/src/stdlib.rs
wdl-analysis/src/stdlib/constraints.rs
wdl-analysis/src/types.rs
wdl-analysis/src/types/v1.rs
wdl-engine/CHANGELOG.md
wdl-engine/Cargo.toml
wdl-engine/src/diagnostics.rs
wdl-engine/src/engine.rs
wdl-engine/src/eval.rs
wdl-engine/src/eval/v1.rs
wdl-engine/src/inputs.rs
wdl-engine/src/lib.rs
wdl-engine/src/value.rs
wdl-engine/tests/inputs.rs
wdl-grammar/CHANGELOG.md
wdl-grammar/src/grammar/v1.rs
wdl-grammar/src/tree.rs

This PR implements expression evaluation in `wdl-engine` with the exception of function calls, which are dependent upon an upcoming implementation of the WDL standard library.
Additionally, certain WDL 1.2 features (such as task variables) and call output access expressions haven't been fully implemented yet; those require changes to the representation of WDL values, which will be completed alongside task and workflow evaluation.
These changes also include some refactorings:
* String interning was removed from `Engine` as it complicated the API; we can reintroduce interning of strings if it proves necessary. This change removed the requirement that values needed to be constructed via the engine.
* Likewise, values are no longer stored in an arena to simplify the API.
* An …

feat: implement expression evaluation in `wdl-engine`.

---

Cargo.toml
wdl-engine/CHANGELOG.md
wdl-engine/Cargo.toml
wdl-engine/src/diagnostics.rs
wdl-engine/src/eval/v1.rs
wdl-engine/src/stdlib.rs
wdl-grammar/src/diagnostic.rs

This commit implements the following functions in the WDL standard library:
* `find`
* `matches`
* `sub`
Additionally, the spans of the arguments are now passed into the functions so that any returned diagnostics may point at a particular argument.

feat: implement the string functions in the WDL standard library.

---

wdl-engine/CHANGELOG.md
wdl-engine/src/eval/v1.rs
wdl-engine/src/stdlib.rs
wdl-engine/src/stdlib/prefix.rs
wdl-engine/src/stdlib/quote.rs
wdl-engine/src/stdlib/sep.rs
wdl-engine/src/stdlib/squote.rs
wdl-engine/src/stdlib/suffix.rs
wdl-engine/src/stdlib/write_tsv.rs
wdl-engine/src/value.rs

This PR implements the following functions from the WDL standard library:
* `prefix`
* `suffix`
* `quote`
* `squote`
* `sep`

feat: implement the string array functions from the WDL standard library.

---

wdl-analysis/CHANGELOG.md
wdl-analysis/src/stdlib.rs
wdl-analysis/src/stdlib/constraints.rs
wdl-analysis/src/types.rs
wdl-analysis/src/types/v1.rs
wdl-analysis/tests/analysis/common-types/source.wdl
wdl-engine/CHANGELOG.md
wdl-engine/src/eval/v1.rs
wdl-engine/src/stdlib.rs
wdl-engine/src/stdlib/as_map.rs
wdl-engine/src/stdlib/as_pairs.rs
wdl-engine/src/stdlib/collect_by_key.rs
wdl-engine/src/stdlib/contains_key.rs
wdl-engine/src/stdlib/keys.rs
wdl-engine/src/stdlib/prefix.rs
wdl-engine/src/stdlib/quote.rs
wdl-engine/src/stdlib/read_map.rs
wdl-engine/src/stdlib/sep.rs
wdl-engine/src/stdlib/size.rs
wdl-engine/src/stdlib/squote.rs
wdl-engine/src/stdlib/suffix.rs
wdl-engine/src/stdlib/values.rs
wdl-engine/src/stdlib/write_map.rs
wdl-engine/src/stdlib/write_object.rs
wdl-engine/src/stdlib/write_objects.rs
wdl-engine/src/stdlib/write_tsv.rs
wdl-engine/src/value.rs

This PR implements the following WDL standard library functions:
* `as_pairs`
* `as_map`
* `keys`
* `contains_key`
* `values`
* `collect_by_key`
It also corrects a few issues discovered during testing:
* Map values in `wdl-engine` should accept `None` for a key.
* Common type calculation now supports discovering common types between the
compound types containing `Union` and `None` as inner types, e.g.
`Array[String] | Array[None] -> Array[String?]`
* The "required primitive type" constraint has been removed as every place the
constraint was used should allow for optional primitive types as well;
consequently, the `AnyPrimitiveTypeConstraint` was renamed to simply
`PrimitiveTypeConstraint`.
* The common type calculation now favors the "left-hand side" of the
calculation rather than the …

feat: implement the generic map functions from the WDL standardy library.

---

Arena.toml
CONTRIBUTING.md
gauntlet/CHANGELOG.md
gauntlet/src/lib.rs
gauntlet/src/main.rs
wdl-engine/src/eval/v1.rs
wdl-engine/tests/inputs.rs
wdl-grammar/src/lexer.rs
wdl-lint/src/rules/blank_lines_between_elements.rs
wdl-lint/src/rules/nonmatching_output.rs
wdl/src/lib.rs

feat: break `refresh` opt into `bless` and `update`

---

.gitignore
Cargo.toml
README.md
wdl-doc/CHANGELOG.md
wdl-doc/Cargo.toml
wdl-doc/src/lib.rs
wdl-doc/src/parameter.rs
wdl-doc/src/struct.rs
wdl-doc/src/task.rs
wdl-doc/src/workflow.rs
wdl-doc/tests/codebase/data_structures/flag_filter.wdl
wdl-doc/tests/codebase/data_structures/read_group.wdl
wdl-doc/tests/doc.rs
wdl-doc/tests/output_docs/data_structures/flag_filter/FlagFilter-struct.html
wdl-doc/tests/output_docs/data_structures/flag_filter/index.html
wdl-doc/tests/output_docs/data_structures/flag_filter/validate_flag_filter-workflow.html
wdl-doc/tests/output_docs/data_structures/flag_filter/validate_string_is_12bit_oct_dec_or_hex-task.html
wdl-doc/tests/output_docs/data_structures/read_group/ReadGroup-struct.html
wdl-doc/tests/output_docs/data_structures/read_group/get_read_groups-task.html
wdl-doc/tests/output_docs/data_structures/read_group/index.html
wdl-doc/tests/output_docs/data_structures/read_group/read_group_to_string-task.html
wdl-doc/tests/output_docs/data_structures/read_group/validate_read_group-task.html
wdl/Cargo.toml
wdl/src/bin/wdl.rs
wdl/src/lib.rs

This is a _very_ rough init commit for `wdl-doc`. All the current HTML output is going to be thrown out and reimplemented once we have the templates from the designers, so I wouldn't spend much time combing through that with a fine-tooth comb.
The most important bit included in this PR is the resulting output directory structure created in `wdl-doc/src/lib.rs`.

feat: init wdl-doc

---

wdl-ast/CHANGELOG.md
wdl-ast/src/v1/task.rs

fix(strip_whitespace): conditionally strip chars from first line

---

wdl-ast/CHANGELOG.md
wdl-ast/src/v1/expr.rs

Applies the #271 fix to multiline strings as well as command sections.

fix: conditionally strip chars from first line

---

gauntlet/src/lib.rs
wdl-analysis/CHANGELOG.md
wdl-analysis/src/analyzer.rs
wdl-analysis/tests/analysis.rs
wdl-doc/src/lib.rs
wdl-engine/tests/inputs.rs
wdl-engine/tests/tasks.rs
wdl-lsp/src/server.rs
wdl/src/bin/wdl.rs

This commit refactors the `new` and `new_with_validator` methods of `Analyzer` to directly accept the `DiagnosticsConfig` rather than an iterator of rules which it immediately uses to create a `DiagnosticsConfig` internally.
By having the `DiagnosticsConfig` (which is `Copy`) passed in directly, we don't have to borrow a rule exception list that might also be used as part of the validator closure passed to `new_with_validator`, sparing us a clone.

refactor: make `Analyzer` accept the diagnostics configuration.

---

wdl-engine/CHANGELOG.md
wdl-engine/src/inputs.rs

Require file path existence for successful input validation parse.

revise: file existence for input validation

---

wdl-engine/CHANGELOG.md
wdl-engine/src/inputs.rs
wdl-engine/tests/inputs/missing-workflow-input/error.txt

This fixes a regression in validating workflow inputs caused by an incorrect `false` when `true` should have been used; the regression was introduced in PR #282.

fix: fix a regression caused by #282.

---

wdl-format/CHANGELOG.md
wdl-format/src/v1/struct.rs
wdl-format/tests/format/issue-289/source.formatted.wdl
wdl-format/tests/format/issue-289/source.wdl

Fixes issue #289 by removing a bad call to `end_line()`.

fix: remove extra end_line() call

---

wdl-ast/CHANGELOG.md
wdl-ast/src/v1/expr.rs
wdl-ast/src/v1/task.rs
wdl-lint/src/rules/preamble_formatting.rs
wdl-lint/src/rules/version_formatting.rs

This fixes whitespace stripping for both commands and multiline strings that left a trailing carriage return when using Windows line endings.
Also fixes the calculation of diagnostic spans for the preamble and version formatting lints when Windows line endings are used.
This should unblock PR #285.

fix: remove trailing carriage return when stripping whitespace.

---

wdl-format/tests/format.rs

Expands format tests to also test idempotency - `format(format(source)) == format(source)`
Addresses #278

test: add format idempotency test

---

gauntlet/Cargo.toml
wdl-analysis/CHANGELOG.md
wdl-analysis/Cargo.toml
wdl-ast/CHANGELOG.md
wdl-ast/Cargo.toml
wdl-doc/CHANGELOG.md
wdl-doc/Cargo.toml
wdl-engine/CHANGELOG.md
wdl-engine/Cargo.toml
wdl-format/CHANGELOG.md
wdl-format/Cargo.toml
wdl-grammar/CHANGELOG.md
wdl-grammar/Cargo.toml
wdl-lint/CHANGELOG.md
wdl-lint/Cargo.toml
wdl-lsp/CHANGELOG.md
wdl-lsp/Cargo.toml
wdl/CHANGELOG.md
wdl/Cargo.toml

running `ci bump` manually to get around failing github action

release: bump versions

---

wdl/CHANGELOG.md
wdl/src/cli.rs

This PR fixes the `wdl run` command to properly join input paths relative to the inputs file.
The code to make the path of the inputs file absolute was incorrectly done, resulting in the later `join_paths` call to effectively be a no-op when the inputs file path on the command line was relative to CWD (e.g. `./foo.json`).
As a result, task execution would fail when using the path as the path would then be treated as relative to the task's working directory as it was not made absolute.
The fix is to simply return the absolute path correctly from `parse_inputs`.
Fixes #301. …

fix: `wdl run` should join input paths correctly.

---

wdl-analysis/RULES.md
wdl-analysis/src/rules.rs

Adds documentation of analysis rules.

docs: analysis rules

---

wdl-analysis/src/lib.rs
wdl-analysis/src/rules.rs

#303 inlined the RULES.md file in a module that doesn't render on docs.rs. This is a fix.

docs: move inlined RULES.md into a public mod

---

wdl-engine/CHANGELOG.md
wdl-engine/src/eval/v1/workflow.rs
wdl-engine/tests/workflows.rs
wdl/CHANGELOG.md
wdl/Cargo.toml
wdl/src/bin/wdl.rs
wdl/src/cli.rs

This PR implements reporting progress during `wdl run`. The `WorkflowEvaluator` now accepts a callback that is called when a task or workflow is evaluated and when it is completed.
The progress bar displayed by `wdl run` has been updated to print out the number of completed tasks, the number of in-process tasks, including up to 10 names of tasks currently being executed.
Additionally, this changes the progress bars displayed by `wdl` to target stdout so that it isn't interleaved with log output on stderr.
The default log level for `wdl` is now `warn` rather than `error` (one less `-v` option required to get to useful log output).
`wdl run` now prefers to run the workflow in a document containing a single workflow and a single task, when not provided either a path to an inputs file or the …

feat: report progress during `wdl run`.

---

.github/pull_request_template.md
wdl-lint/CHANGELOG.md
wdl-lint/src/rules/comment_whitespace.rs
wdl-lint/tests/lints/comment-whitespace/source.errors

This pull request ~adds~ modifies a ~new~ rule to `wdl-lint`.
- **Rule Name**: `CommentWhitespace`
_Describe the rules you have implemented and link to any relevant issues._
Relaxes `CommentWhitespace` to fix #313 
possible diagnostic emitted for the rule within the file where the rule
overridden that callback method for the special `Validator`
(`wdl-ast/src/validation.rs`) and `LintVisitor`
(`wdl-lint/src/visitor.rs`) visitors. These are required to ensure the new
visitor callback will execute. …

revise: relax CommentWhitespace lint

---

wdl-ast/CHANGELOG.md
wdl-ast/src/v1/task.rs
wdl-lint/CHANGELOG.md
wdl-lint/src/rules/shellcheck.rs
wdl-lint/src/util.rs
wdl-lint/tests/lints/shellcheck-warn/source.errors
wdl-lint/tests/lints/shellcheck-warn/source.wdl

This PR addresses the bug described in #307, wherein shellcheck highlight spans were sometimes misplaced. This was due to incorrect counting of the amount of leading whitespace stripped by `CommandSection::strip_whitespace`. To avoid duplicating logic from the aforementioned method, the whitespace counting portion was refactored into a separate method, `count_whitespace` so that both `strip_whitespace` and `sanitize_command` can make use of it. 

fix: misplaced shellcheck spans

---

wdl-engine/CHANGELOG.md
wdl-engine/src/backend.rs
wdl-engine/src/backend/local.rs
wdl-engine/src/eval.rs
wdl-engine/src/eval/v1/expr.rs
wdl-engine/src/eval/v1/task.rs
wdl-engine/src/eval/v1/workflow.rs
wdl-engine/src/inputs.rs
wdl-engine/src/value.rs

This PR implements the calculation of mount points for task execution backends that use containers.
Paths from `File` and `Directory` values that are visible prior to evaluating the command section of a task are added to a `PathTrie`.
The `PathTrie` is used to determine the minimum number of mounts in the guest environment to be able to send input files to the container.
Command evaluation does a translation from host paths to guest paths so that the generated command script uses only guest paths.
Similarly, evaluation of output values does a translation from guest paths to host paths so that tasks always output the host path.
Fixes #267. …

feat: implement mount points for task execution.

---

.gitattributes

This PR excludes the `inconsistent-newlines` test source from autocrlf behavior by git.

chore: update `.gitattributes` for inconsistent newline lint test.

---

deny.toml

This update ignores the RUSTSEC advisory for the `paste` crate.
While the crate is no longer maintained, it is a relatively small crate that is used primarily for generating identifiers in macros.
We use it in AST for generating some boiler plate implementations on AST types.

chore: update deny.toml.

---

Gauntlet.toml
wdl-analysis/CHANGELOG.md
wdl-analysis/src/diagnostics.rs
wdl-analysis/src/document/v1.rs
wdl-analysis/tests/analysis/allow-nested-inputs-1.0/source.diagnostics
wdl-analysis/tests/analysis/allow-nested-inputs-1.1/source.diagnostics
wdl-analysis/tests/analysis/allow-nested-inputs-1.2/source.diagnostics

This pull request adds a feature to `wdl-analysis`.
- In the meta section of the workflow when `allowedNestedInputs` is true, this function emits a warning for missing inputs.
For the import 
```
workflow my_workflow {
meta {
allowNestedInputs: true
}
call my_task
call my_task as my_task2 { input: required = "required" }
call my_task as my_task3 { input: required = "required", optional = "optional", defaulted = "defaulted" }
}
```
```
warning: missing required call input `required` for task `my_task`
┌─ tests/analysis/allow-nested-inputs-1.0/source.wdl:22:10
│
22 │     call my_task
│          ^^^^^^^
```
["keep a …

feat: `missing_call_input` warning

---

wdl-analysis/src/document/v1.rs
wdl-analysis/src/eval/v1.rs
wdl-engine/CHANGELOG.md
wdl-engine/src/eval/v1/workflow.rs
wdl-engine/src/inputs.rs

This pull request fixes an issue in `wdl-engine `where workflow input dependencies were not being handled correctly during graph evaluation.
- update `WorkflowGraphBuilder` to skip dependency edges for provided inputs to enable parallel task execution when dependencies are satisfied
- add unit tests to verify graph structure with and without provided inputs, using example given in #356 
Closes: #356

fix: handle input dependencies in workflow graph evaluation

---

ci/src/main.rs
wdl-ast/src/element.rs
wdl-ast/src/v1/expr.rs
wdl-doc/src/callable.rs
wdl-format/src/v1/expr.rs

Fixes some renamed types and a few other warnings from `cargo doc`.

fix: eliminate `cargo doc` warnings.

---

wdl-lsp/CHANGELOG.md
wdl-lsp/src/server.rs

This pull request fixes the current way of handling URLs in `textDocument/didOpen` event
If i open a single `wdl` file the analyzer can't _add_ the file as currently the analyzer doesn't check if the `URL` it got is a file or a directory, it just assumes its a directory and calls `analyzer.add_directory()`  instead of `analyzer.add_document()`
Error log:
```
2026-03-20T01:10:20.308154Z ERROR wdl_lsp::server: failed to add document file:///home/kiit/dev/stjude-rust-labs/sprocket-vscode/syntaxes/example.wdl: `/home/kiit/dev/stjude-rust-labs/sprocket-vscode/syntaxes/example.wdl` is a file, not a directory
``` …

fix: lsp errors out when a file uri is received instead of directory

---

wdl-engine/CHANGELOG.md
wdl-engine/src/config.rs
wdl-engine/src/eval/v1/task.rs
wdl-engine/src/eval/v1/workflow.rs
wdl-engine/src/http.rs
wdl-engine/src/http/azure.rs
wdl-engine/src/http/google.rs
wdl-engine/src/http/gs.rs
wdl-engine/src/http/s3.rs

This commit implements support for cloud storage URIs:
* `az://<account>/<container>/<blob>` for Azure Blob Storage
* `s3://<bucket>/<object>` for AWS S3
* `gs://<bucket>/<object>` for Google Cloud Storage
Additionally, the configuration format has been updated to include sections on authentication tokens for the different services.
The authentication tokens are the query strings for presigned URLs.
This allows the engine configuration to store only a signature that grants access to a resource without storing the storage account keys.
As we aren't yet localizing inputs for local task executions, the support for these URLs is currently limited to the `read_*` functions from the WDL standard library; once input localization is properly implemented, you'll be able to use these URIs in an …

feat: support cloud storage URIs in the downloader.

---

.github/workflows/stale.yml

Adds an action to comment and close stale pull requests.

chore: adds an action to close stale PRs

---

wdl-lint/CHANGELOG.md
wdl-lint/src/tags.rs

Tags now implement `TryFrom`, this will be used in `sprocket explain` for parsing tags through cli

feat: Tags now implement TryFrom

---

Cargo.toml
wdl/CHANGELOG.md

This PR updates two crates we own (`crankshaft` and `http-cache-stream-reqwest`) to official, upstreamed versions on crates.io.

revise: updates dependencies to stable versions

---

wdl-ast/src/v1/import.rs
wdl-lint/src/rules/comment_whitespace.rs
wdl-lint/src/rules/key_value_pairs.rs

A new Rust version was released today with a helpful lint of calling `next_back` instead of `last` on double-ended iterators.
This fixes those calls.

chore: fix clippy warnings.

---

gauntlet/CHANGELOG.md
gauntlet/src/config/inner.rs
gauntlet/src/lib.rs

This PR fixes an issue in `gauntlet` where diagnostic messages were being handled differently on Windows versus Unix-based systems, causing CI failures. I implemented a normalization function to ensure consistent handling of paths, line endings, and OS-specific error messages across platforms.

Fix gauntlet diagnostics windows

---

wdl-engine/CHANGELOG.md
wdl-engine/src/backend.rs

This PR fixes a bug where a task manager state is unlimited is incorrectly calculated.

fix: fixes the calculation of an unlimited state

---

.github/workflows/stale.yml

The `stale` CI action currently checks the last update date. Based on experience, that date doesn't reflect the last visible action on a PR. This PR switches that to check the last push date for a PR.

refactor: check push date rather than update date

---

.github/workflows/labels.yml

The current labels CI step fails when the PR originates in a public fork. This is because the GitHub token that the CI steps use is limited to read-only access (see the last column in this table: https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#permissions-for-the-github_token). This PR changes the event type to `pull_request_target`, which causes the job to run in the base context (e.g. our repo)(documentation: https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#permissions-for-the-github_token). This allows the permissions to be elevated, since it prevents unknowingly running potentially malicious code.
Quoting from the docs:
> This event runs in the context of the base …

fix: change event type for labels CI to run in base context

---

Arena.toml
wdl-lint/CHANGELOG.md
wdl-lint/src/rules/preamble_comment_placement.rs
wdl-lint/tests/lints/preamble-comment-after-version/source.errors

`wdl-lint` should never emit errors, but the `PreambleCommentPlacement` rule was configured at error severity.

fix: severity downgrade from error to note

---

.github/workflows/pr_assign.yml

The GitHub command line utility requires permissions on the organization to set reviewers because it attempts to do a union with any existing reviewers. This is documented in: https://github.com/cli/cli/issues/4844. It doesn't appear that it will be resolved anytime soon. Instead of creating a PAT with the elevated permissions, this PR avoids the issue by using the API directly and not attempting to do any reconciliation. It simply loops over the reviewers and requests them one at a time. It intentionally silences any errors as this shouldn't cause the CI to be red on new PRs.

ci: switch reviewers assignment to use API and always succeed

---

wdl/CHANGELOG.md
wdl/src/cli.rs

> #@ except lint directives within WDL source should still require an exact case sensitive match, but I think we can relax that requirement on the CLI.
ref: https://github.com/stjude-rust-labs/sprocket/issues/95
Checking of rules were done inside wdl cli crate instead of sprocket.
I think the change should be inside this repository, but do let me know if i have to make changes in `sprocket` instead

refactor: accept case insensitive `--except` args

---

.github/workflows/pr_assign.yml

It appears that the `gh pr` command line utility cannot assign pull requests to an external contributor. This switches to using the API to do it, which works (at least locally). It also adds `|| true` so that the step cannot fail and break the CI.

ci: use API for assignee

---

.github/workflows/pr_assign.yml
wdl-engine/CHANGELOG.md
wdl-engine/src/stdlib/sub.rs
wdl-engine/tests/tasks/test-sub/outputs.json

The WDL [spec](https://github.com/openwdl/wdl/blob/wdl-1.2/SPEC.md#sub) specifies replacement of all non-overlapping matches. This PR updates the `regex` function from `replace` to `replace_all` to make it compliant with the spec.

fix: perform multiple replacements with sub()

---

wdl-engine/src/backend/crankshaft.rs

closes: #427
confirmed it was causing an error:
```bash
➜  wdl git:(chown-absolute-path) ✗ cargo run --bin wdl --features="cli" run test.wdl -o chown
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.18s
Running `target/debug/wdl run test.wdl -o chown`
2025-04-19T19:32:14.736909Z ERROR wdl_engine::backend::crankshaft: receiving result for cleanup task 'wdl-engine-chown-cleanup-VLWFAxUKzP3K' failed: Docker responded with status code 500: chown is not an absolute path
2025-04-19T19:32:14.737078Z ERROR wdl_engine::backend::crankshaft: cleanup task failed: receiving result for cleanup task 'wdl-engine-chown-cleanup-VLWFAxUKzP3K' failed: Docker responded with status code 500: chown is not an absolute path
{
"out_f": "/home/dead/dev/stjude-rust-labs/wdl/chown/calls/t/attempts/0/wor …
```

fix: `output` mount path must be absolute

---

wdl-engine/CHANGELOG.md
wdl-engine/src/eval/v1/workflow.rs
wdl-engine/tests/tasks.rs
wdl-engine/tests/workflows.rs
wdl-engine/tests/workflows/callstack/error.txt
wdl-engine/tests/workflows/callstack/first.wdl
wdl-lint/tests/lints.rs

This fixes call locations in a printed callstack displaying overly verbose diagnostics due to using the entire span of the call statement; call statements typically span many lines due to their inputs, leading to overly verbose output.
The fix is to use the span of the call keyword in the call statement, which guarantees only a single line of source output per call location.
This also includes a change to the evaluation tests so that invalid WDL gets a failure message rather than writing to `errors.txt`. Additionally, the printed output of the lint tests harness has been updated to match what we output for the other test harnesses. …

fix: call locations spans should not span multiple lines.

---

Cargo.toml
wdl-ast/CHANGELOG.md
wdl-engine/CHANGELOG.md
wdl-engine/src/backend.rs
wdl-engine/src/backend/docker.rs
wdl-engine/src/backend/local.rs
wdl-engine/src/config.rs
wdl-engine/src/eval.rs
wdl-engine/src/eval/v1.rs
wdl-engine/src/eval/v1/task.rs
wdl-engine/src/eval/v1/workflow.rs
wdl-engine/src/stdlib.rs
wdl-engine/tests/tasks.rs
wdl-engine/tests/tasks/task-fail/error.txt
wdl-engine/tests/workflows.rs
wdl-engine/tests/workflows/callstack/error.txt
wdl-grammar/CHANGELOG.md
wdl/CHANGELOG.md

This commit renames the `crankshaft` backend to simply the `docker` backend and removes the TODOs that were in place for the upcoming TES backend, which will now be introduced as a separate backend given the number of differences between the two backends (mostly due to how it handles inputs, outputs, and localization).
Additionally, this updates `wdl-engine` to use `crankshaft` version `0.2.0`, which required some changes in the (now) docker backend for handling stdout and stderr.
Additionally, the backend configuration for the engine has subsequently changed so that it no longer just wraps a Crankshaft configuration verbatim, allowing for a stable configuration format driven by `wdl-engine`. The backend configuration is now an enumeration rather than a set of structs, allowing for a …

refactor: rename `crankshaft` backend to `docker`.

---

wdl-engine/CHANGELOG.md
wdl-engine/src/eval/v1.rs
wdl-engine/src/eval/v1/task.rs
wdl-engine/src/eval/v1/workflow.rs
wdl-engine/src/inputs.rs

This commit writes an `inputs.json` and a `outputs.json` for each task and workflow that is evaluated.
The files are present in each root directory for the task/workflow in the `outputs` directory.
Closes #330.

feat: write inputs and outputs to task/workflow root directories.

---

wdl-cli/CHANGELOG.md
wdl-cli/src/analysis.rs

This PR fixes the bug where the `shellcheck` option is still provided on `wdl-cli::Analysis`.

fix: removes unused `shellcheck` option

---

ci/src/main.rs
wdl-analysis/src/document/v1.rs
wdl-ast/CHANGELOG.md
wdl-ast/src/v1/workflow.rs

If a WDL >=v1.2 workflow has a non-boolean value for the ,"allow nested inputs" hint, the metadata will also be searched for `allowNestedInputs: <bool>` instead of prematurely dis-allowing nested inputs

revise: clarity around "allow nested inputs"

---

wdl-doc/src/docs_tree.rs
wdl-doc/theme/dist/style.css
wdl-doc/theme/src/main.css
wdl-doc/theme/src/markdown.css

Load a CSS styling preset resembling Github's markdown rendering. Just requires adding a `markdown-body` class to the element for markdown elements to be styled. Example. Leverages an existing minimal markdown theme from [github-markdown-css](https://github.com/sindresorhus/github-markdown-css?tab=readme-ov-file), but copied into the project to avoid an extra build step.

feat: add markdown styling

---

wdl-engine/CHANGELOG.md
wdl-engine/src/backend/docker.rs
wdl-engine/src/backend/tes.rs
wdl-engine/tests/tasks.rs
wdl-engine/tests/tasks/path-translation/source.wdl

This PR fixes the guest paths used for logging the command's stdout and stderr to for both the Docker and TES backends.
For the TES backend, creating files at root do not work for some TES server implementations.

fix: use `/var/log` directory for stdout/stderr guest paths.

---

wdl-analysis/CHANGELOG.md
wdl-analysis/Cargo.toml
wdl-analysis/src/analyzer.rs
wdl-analysis/src/document.rs
wdl-analysis/src/document/v1.rs
wdl-analysis/src/handlers.rs
wdl-analysis/src/handlers/goto_definition.rs
wdl-analysis/src/lib.rs
wdl-analysis/src/queue.rs
wdl-analysis/src/types.rs
wdl-lsp/src/server.rs

Added:
- `Struct definitions`
- `Call definitions`
- Tasks
- Workflows
- `Namespaced calls`
- `Namespace usage → import declaration`
- `Access expressions`
- Struct member access
- Call output access
- Array element access
- Chained access expressions
- `Scope-based resolution`
- Variable references
- Scatter variables
- Conditional variables
- Task inputs/outputs
- Workflow inputs/outputs
- `Cross document navigation`
- `Aliased imports`
- `Global document resolution`

feat: add support for lsp `goto_definitions`

---

.github/CODEOWNERS

Updating the CODEOWNERS file for the new Github team name

chore: change github CODEOWNER name

---

wdl-lsp/CHANGELOG.md
wdl-lsp/src/server.rs

Hi, so i was working on lsp tests and i found out they were flaky. The LSP server was responding to the `initialize` request before its initial workspace analysis was complete which created a race condition where a client could send a feature request (e.g., `textDocument/gotoDefinition`) before the server had the necessary data to handle it.
This was most visible in the integration test suite, which would fail with errors like `"document not found in graph"` or `"document has not been parsed"`.
This pr fixes it by making the server's `initialize` handler `await` the completion of the initial workspace analysis. …

fix: ensure server is fully initialized before responding

---

ci/src/main.rs
gauntlet/src/config.rs
gauntlet/src/config/inner.rs
gauntlet/src/main.rs
gauntlet/src/report.rs
gauntlet/src/repository.rs
wdl-ast/tests/registry.rs
wdl-cli/src/inputs.rs
wdl-doc/src/lib.rs
wdl-doc/tests/doc.rs
wdl-engine/src/http.rs
wdl-engine/src/tree.rs
wdl-format/src/config/indent.rs
wdl-format/src/config/max_line_length.rs
wdl-format/src/lib.rs
wdl-format/src/token/pre.rs
wdl-grammar/tests/parsing.rs
wdl-lint/src/lib.rs
wdl-lint/src/rules/concise_input.rs
wdl-lint/src/rules/import_sorted.rs
wdl-lint/src/rules/input_sorted.rs
wdl-lint/src/rules/line_width.rs
wdl-lint/src/rules/lint_directive_formatted.rs
wdl-lint/src/rules/output_section.rs
wdl-lint/src/rules/parameter_meta_matched.rs
wdl-lint/src/rules/shellcheck.rs
wdl-lint/src/tags.rs

These are basically all [this new lint](https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args) for format string arguments

chore: apply clippy lints from Rust 1.88

---

wdl-lint/CHANGELOG.md
wdl-lint/src/rules/shellcheck.rs

The current handling of placeholders is buggy. The tree treats a placeholder as a component of the string, but also as a child expression. The prior logic descends into the string, looking at children, but any additional quotation is not a child node. So we just store the expressions associated with placeholders and then skip those when evaluating child nodes.

fix: skip `Expr::NameRef` if already seen as `StringPart::Placeholder`

---

ci/src/main.rs

this is inconsequential due to the retry logic in the `ci` bin, but if we want our release time to shorten by 30 seconds, we can merge this 😅 

ci: move `wdl-lint` to match topological order

---

wdl-engine/CHANGELOG.md
wdl-engine/src/config.rs

This PR fixes `Config` to use `IndexMap` internally rather than `HashMap` so that the output of `sprocket config` commands is stable.

fix: use `IndexMap` in `Config`.

---

wdl-engine/CHANGELOG.md
wdl-engine/src/backend.rs
wdl-engine/src/backend/docker.rs
wdl-engine/src/eval/v1/task.rs

The changes in #605 made the assertion of the work directory being local in the wrong place, which impacted the TES backend and caused a panic.
The fix is to take cleanup by an `EvaluationPath` which may be local or remote; the assertion was moved to the Docker backend where the path should always be local.

fix: correct assertion for TES backend.

---

wdl-cli/CHANGELOG.md
wdl-cli/Cargo.toml
wdl-engine/CHANGELOG.md
wdl-engine/Cargo.toml
wdl/CHANGELOG.md
wdl/Cargo.toml

release: bump `wdl-engine` to `0.8.1`.
