stjude-rust-labs/wdl

lint-rules.md

Here we have it! The first draft of our comprehensive lint rule set. There are some controversial rules in here, so I expect a bit of debate to go down. I opted to open this PR directly instead of sharing in our Slack channel, as it will be good to have public record of _why_ we chose to enforce what we decide on. I doubt this document gets through review without a few rounds of revision.
This is **not** any kind of document we should feel beholden to in the future. As stated in the document, these rules are "up for debate" for now. In my imagining, we won't consider a rule "settled" until someone actually _implements_ the rule in code. As such, I would more think of this as a document to spark thought and debate. Maybe act as a reference for anyone who wants "cement" a rule in code.
So …

feat: first draft of lint rules document

---

.gitignore
rust-toolchain.toml

Adds a toolchain.toml file to specify the requirement on the nightly toolchain to build the source. Resolves #8 

chore: adds toolchain.toml for nightly channel

---

Arena.toml
wdl-grammar/CHANGELOG.md
wdl-grammar/src/v1/lint/snake_case.rs

This pull request ~adds a new~ modifies a rule to `wdl`.
- **Rule Name**: `snake_case`
- **Rule Kind**: Lint warning
- **Rule Code**: `v1::W006`
- **Packages**: `wdl-grammar`
_Describe the rules you have implemented and link to any relevant issues._
Permits lowercase letters and digits to be next to each other without an underscore.
tables (`wdl-ast/src/v1.rs` for AST-based rules and 
`wdl-grammar/src/v1.rs` for parse tree-based rules).
table at `RULES.md`.
- Validation rules added to `wdl-ast` should be added to `fn rules()` within 
`wdl-ast/src/v1/validation.rs`.
- Lint rules added to `wdl-ast` should be added to `fn rules()` within `wdl-ast/src/v1/lint.rs`.
- Validation rules …

fix(wdl-grammar): false positive cases in SnakeCase rule

---

RULES.md
wdl-ast/CHANGELOG.md
wdl-ast/src/v1.rs
wdl-ast/src/v1/lint/matching_parameter_meta.rs
wdl-core/CHANGELOG.md
wdl-core/src/concern/lint.rs
wdl-grammar/CHANGELOG.md
wdl-grammar/src/v1.rs
wdl-grammar/src/v1/lint/document_preamble.rs
wdl-grammar/src/v1/lint/double_quotes.rs
wdl-grammar/src/v1/lint/missing_runtime_block.rs
wdl-grammar/src/v1/lint/mixed_indentation.rs
wdl-grammar/src/v1/lint/newline_eof.rs
wdl-grammar/src/v1/lint/no_curly_commands.rs
wdl-grammar/src/v1/lint/one_empty_line.rs
wdl-grammar/src/v1/lint/preamble_comment.rs
wdl-grammar/src/v1/lint/snake_case.rs
wdl-grammar/src/v1/lint/whitespace.rs

Conform to definition of `body` as outlined in #12 . This PR has minimal code changes, but significant docs changes. Please feel free to nitpick over language/wording/etc. This will form the basis of future documentation and should be our source of truth.

feat: body matches definition in #12

---

README.md

chore: update README with information about the `wdl` CLI tool.

---

wdl-lint/RULES.md
wdl-lint/src/v1.rs
wdl-lint/src/v1/import_whitespace.rs
wdl-lint/tests/lints/import-whitespace/source.errors
wdl-lint/tests/lints/import-whitespace/source.wdl

- **Rule Name**: `ImportWhitespace`
_Describe the rules you have implemented and link to any relevant issues._
possible diagnostic emitted for the rule within the file where the rule  

feat: ImportWhitespace rule

---

Arena.toml
Gauntlet.toml

chore: refresh arena and gauntlet

chore: refresh gauntlet and arena

---

wdl-lint/tests/lints.rs

This is needed for easy debugging—else, the tests run in parallel and the debugger jumps around.

revise: introduces a `--serial` option for lint tests

---

.github/workflows/CI.yml
Cargo.toml
README.md
wdl-analysis/CHANGELOG.md
wdl-analysis/Cargo.toml
wdl-ast/CHANGELOG.md
wdl-ast/Cargo.toml
wdl-gauntlet/Cargo.toml
wdl-grammar/CHANGELOG.md
wdl-grammar/Cargo.toml
wdl-lint/CHANGELOG.md
wdl-lint/Cargo.toml
wdl/CHANGELOG.md
wdl/Cargo.toml

Also updates the README with information about our MSRV policy and instructions for updating.

chore: add a MSRV to each crate and CI job to verify.

---

wdl-gauntlet/Cargo.toml

fix: fix the build break.

---

Arena.toml
Gauntlet.toml
gauntlet/CHANGELOG.md
gauntlet/Cargo.toml
gauntlet/src/config/inner.rs
gauntlet/src/document/identifier.rs
gauntlet/src/lib.rs
gauntlet/src/repository.rs

feat: gauntlet does a full analysis

---

.github/workflows/release.yml

ci: use right ENV var

---

wdl-format/Cargo.toml
wdl-format/src/config.rs
wdl-format/src/config/builder.rs

fix: 'new()' method for format Config Builder

---

wdl-format/CHANGELOG.md
wdl-format/Cargo.toml
wdl-format/src/v1/decl.rs
wdl-format/tests/format/optional_structs/source.formatted.wdl
wdl-format/tests/format/optional_structs/source.wdl
wdl/CHANGELOG.md
wdl/Cargo.toml

fix: don't panic on certain optional types

---

ci/src/main.rs
gauntlet/Cargo.toml
wdl-analysis/CHANGELOG.md
wdl-analysis/Cargo.toml
wdl-ast/CHANGELOG.md
wdl-ast/Cargo.toml
wdl-engine/Cargo.toml
wdl-format/CHANGELOG.md
wdl-format/Cargo.toml
wdl-grammar/CHANGELOG.md
wdl-grammar/Cargo.toml
wdl-lint/CHANGELOG.md
wdl-lint/Cargo.toml
wdl-lsp/CHANGELOG.md
wdl-lsp/Cargo.toml
wdl/CHANGELOG.md
wdl/Cargo.toml

release: bump crate versions.

---

wdl/Cargo.toml
wdl/src/lib.rs

We'll add it back when `wdl-engine` is ready for release.

chore: remove `wdl-engine` dependency from `wdl`.

---

wdl-lint/RULES.md

The `RULES.md` file got out of date. Reiterating something we all know, this isn't a sustainable documentation solution. Not sure the exact priority for updating `sprocket.bio` with pages for each rule, but that is the end-game here.

docs: Update RULES.md

---

wdl-analysis/CHANGELOG.md
wdl-analysis/Cargo.toml
wdl-analysis/src/analyzer.rs
wdl-analysis/src/queue.rs
wdl-lsp/CHANGELOG.md
wdl-lsp/Cargo.toml
wdl-lsp/src/server.rs

This PR is the first of several needed to get formatting working in VSCode.

feat: adds groundwork for formatting in the Sprocket VSCode extension

---

wdl-analysis/src/types.rs
wdl-engine/CHANGELOG.md
wdl-engine/src/eval/v1.rs
wdl-engine/src/stdlib.rs
wdl-engine/src/stdlib/chunk.rs
wdl-engine/src/stdlib/contains.rs
wdl-engine/src/stdlib/cross.rs
wdl-engine/src/stdlib/flatten.rs
wdl-engine/src/stdlib/prefix.rs
wdl-engine/src/stdlib/quote.rs
wdl-engine/src/stdlib/range.rs
wdl-engine/src/stdlib/read_lines.rs
wdl-engine/src/stdlib/read_objects.rs
wdl-engine/src/stdlib/read_tsv.rs
wdl-engine/src/stdlib/select_all.rs
wdl-engine/src/stdlib/select_first.rs
wdl-engine/src/stdlib/squote.rs
wdl-engine/src/stdlib/suffix.rs
wdl-engine/src/stdlib/transpose.rs
wdl-engine/src/stdlib/unzip.rs
wdl-engine/src/stdlib/write_objects.rs
wdl-engine/src/stdlib/write_tsv.rs
wdl-engine/src/stdlib/zip.rs
wdl-engine/src/value.rs

This PR implements the following functions from the WDL standard library:
* `range`
* `transpose`
* `cross`
* `zip`
* `unzip`
* `contains`
* `chunk`
* `flatten`
* `select_first`
* `select_all`

feat: implement the generic array functions from the WDL standard library.

---

Arena.toml
Gauntlet.toml
wdl-analysis/CHANGELOG.md
wdl-analysis/src/analyzer.rs
wdl-analysis/src/diagnostics.rs
wdl-analysis/src/document.rs
wdl-analysis/src/document/v1.rs
wdl-analysis/src/rules.rs
wdl-analysis/src/stdlib.rs
wdl-analysis/src/stdlib/constraints.rs
wdl-analysis/src/types/v1.rs
wdl-analysis/tests/analysis/unnecessary-function-calls/source.diagnostics
wdl-analysis/tests/analysis/unnecessary-function-calls/source.wdl
wdl-engine/CHANGELOG.md
wdl-engine/src/eval/v1.rs
wdl-engine/src/stdlib.rs
wdl-engine/src/stdlib/defined.rs
wdl-engine/src/stdlib/length.rs
wdl-engine/src/stdlib/select_all.rs
wdl-engine/src/stdlib/select_first.rs
wdl-lint/src/lib.rs

This commit implements the following functions from the WDL standard library:
* `defined`
* `length`
Additionally, the `OptionalTypeConstraint` applied to the generic type parameters of the `select_first`, `select_all`, and `defined` functions has been removed; this allows the functions to be called with non-optional types.
Instead, a warning is now emitted by analysis if any of those functions are called with a non-optional type.
This PR completes the standard library implementation in `wdl-engine` 🎉 

feat: implement the `defined` and `length` functions from the WDL standard library.

---

wdl-engine/CHANGELOG.md
wdl-engine/src/eval/v1/task.rs
wdl-engine/src/inputs.rs
wdl-engine/tests/inputs.rs
wdl-engine/tests/inputs/call-input-present/inputs.json
wdl-engine/tests/inputs/call-input-present/source.wdl
wdl-engine/tests/inputs/missing-task-input/error.txt

This PR fixes input validation to not treat specified call inputs as missing.
As type checking the specified call inputs requires full evaluation, this fix treats specified call inputs as valid for the purpose of input validation.
Note that validation requires a static type checking pass, so any statically invalid call inputs will be verified prior to validating call inputs.
When workflow evaluation is fully implemented, input validation will also type check the call inputs (which includes any type checks that cannot be done statically).
Fixes #275. …

fix: fix validation not to treat specified call inputs as missing.

---

Cargo.toml
ci/src/main.rs
wdl-analysis/src/analyzer.rs
wdl-format/src/token/pre.rs
wdl-grammar/src/parser.rs

fix: fix 2024 edition lints for CI.

---

Arena.toml
Gauntlet.toml

Been a while since we updated the commit hashes. This is just the result of running `gauntlet --update` and `gauntlet --update --arena`
We should probably set this up to run automatically once a week or so.

chore: gauntlet --update

---

.github/workflows/bump.yml
ci/src/main.rs

ci: updates to latest

---

.github/workflows/bump.yml
ci/src/main.rs

ci: bump to right version

---

wdl-doc/Cargo.toml

chore(wdl-doc): add description to Cargo.toml

---

Arena.toml
Gauntlet.toml
gauntlet/src/lib.rs

chore: update gauntlet

---

.github/pull_request_template.md
RELEASE.md

docs: update RELEASE.md with latest process

---

.github/workflows/CI.yml
Gauntlet.toml
deny.toml

This crate adds `cargo-deny` and the associated CI check. This is best practice to make sure we always check and explicitly accept any new licenses to our stack.

revise: adds `cargo-deny` and associated CI check

---

README.md

Updates README with better development instructions.
Closes #351 .

docs: add Bash and shellcheck requirement

---

wdl-lint/CHANGELOG.md
wdl-lint/src/tags.rs

ref:
https://github.com/stjude-rust-labs/wdl/pull/374#issuecomment-2762409701

refactor(wdl-lint): replace TryFrom with FromStr

---

gauntlet/CHANGELOG.md
wdl-analysis/CHANGELOG.md
wdl-ast/CHANGELOG.md
wdl-doc/CHANGELOG.md
wdl-engine/CHANGELOG.md
wdl-format/CHANGELOG.md
wdl-grammar/CHANGELOG.md
wdl-lint/CHANGELOG.md
wdl-lsp/CHANGELOG.md
wdl/CHANGELOG.md

This PR changes the `CHANGELOG` files to have a format more amenable to copy and pasting into release notes. Specifically the format used in the latest release. See here - https://github.com/stjude-rust-labs/wdl/releases/tag/wdl-v0.12.0

docs: CHANGELOG formatting

---

.github/workflows/labels.yml

This PR automates the addition and removal of the `S-awaiting-CI` label.

ci: adds auto-labelling pipeline

---

wdl/src/cli.rs

This commit changes `wdl run` so that it displays the progress bar when running a WDL file containing a single task definition.

fix: show progress bar for single task evaluation.

---

.github/pull_request_template.md

see https://github.com/stjude-rust-labs/wdl/pull/401#issuecomment-2787908681 for the view external contributors have

docs: revise part of checklist that external contributors can't do

---

wdl-lint/CHANGELOG.md
wdl-lint/src/lib.rs

this is so that the `sprocket` bin can use this for CL args
(If you are an external contributor without permissions, leave this
unchecked and someone else will do it for you.)
(If you are an external contributor without permissions, leave this
unchecked and someone else will do it for you.)

chore: expose `find_nearest_rule()`

---

.github/pull_request_template.md
CONTRIBUTING.md

Our existing CONTRIBUTING document was a good start. However, now that we have additional experience, we can improve it.
This PR reorganizes and surfaces new contributor information to the top in a new top-level section. It divides out the types of contributions. It sets out a clear policy on pull request reviews. It provides instructions on how to interact with the community and maintainers to avoid duplication of effort. It takes a stance on artificial intelligence (AI) generated submissions. 
(If you are an external contributor without permissions, leave this
unchecked and someone else will do it for you.)
(If you are an external contributor without permissions, leave this
unchecked and someone else will do it for you.)
changes (when …

docs: revise CONTRIBUTING

---

wdl-analysis/CHANGELOG.md
wdl-analysis/Cargo.toml
wdl-analysis/src/diagnostics.rs
wdl-analysis/src/types/v1.rs
wdl-analysis/tests/analysis/static-regex-validation/source.diagnostics
wdl-analysis/tests/analysis/static-regex-validation/source.wdl

Adds static validation of regex and show diagnostics if its invalid.
closes: #253 

feat: validate regular expressions on the go

---

.github/ISSUE_TEMPLATE/bug_report_template.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request_template.md

This PR adds two issue templates. The goal is to prevent incomplete issues with insufficient information. The templates have sections and descriptions to help guide users to providing the information needed to address the issue.
(If you are an external contributor without permissions, leave this
unchecked and someone else will do it for you.)
(If you are an external contributor without permissions, leave this
unchecked and someone else will do it for you.)

chore: issue templates

---

wdl-analysis/CHANGELOG.md
wdl-analysis/src/analyzer.rs
wdl-analysis/src/document.rs
wdl-analysis/src/document/v1.rs
wdl-analysis/src/graph.rs
wdl-analysis/src/queue.rs

closes: #429 
~~working on top of #341~~

fix: prevent lsp crash from single file panics

---

Cargo.toml
wdl-analysis/src/graph.rs
wdl-analysis/src/queue.rs
wdl-engine/CHANGELOG.md
wdl-engine/Cargo.toml
wdl-engine/src/backend.rs
wdl-engine/src/backend/local.rs
wdl-engine/src/backend/tes.rs
wdl-engine/src/config.rs
wdl-engine/src/eval.rs
wdl-engine/src/eval/v1/expr.rs
wdl-engine/src/eval/v1/task.rs
wdl-engine/src/eval/v1/workflow.rs
wdl-engine/src/http.rs
wdl-engine/src/path.rs
wdl-engine/src/stdlib/size.rs
wdl-engine/src/units.rs
wdl-engine/tests/tasks.rs
wdl-engine/tests/workflows.rs
wdl-lint/src/rules/shellcheck.rs

This PR implements a task execution backend that uses the Crankshaft TES backend for sending tasks to a TES server.
The TES backend currently has these limitations:
* The backend fails a task execution if it has an input that is a non-empty directory; this may occur with explicit use of `Directory` type inputs, but also if files are written to a task's `tmp` directory (i.e. from a call to any of the `write_` stdlib functions). In the future, the backend will upload the directory contents to configured cloud storage and specify the input by URL.
* Local input file contents are sent to the TES server directly when creating the task. For large files, this may easily run up against limitations in input and request sizes. In the future, the backend will upload the file to cloud storage and …

feat: implement a TES task execution backend.

---

wdl-engine/src/config.rs

This PR adds an `insecure` option to the TES backend configuration to allow it to accept server URLs with HTTP; the default of the option is `false`, meaning only HTTPS schemed URLs are accepted.

feat: add `insecure` option to TES backend configuration.

---

wdl-doc/src/docs_tree.rs
wdl-doc/src/document.rs
wdl-doc/theme/dist/style.css
wdl-doc/theme/src/main.css

See slack message for changelog

feat: bugfixes and sidebar consistency alignment, part 1

---

wdl-lsp/CHANGELOG.md
wdl-lsp/src/server.rs

in service of https://github.com/stjude-rust-labs/sprocket/issues/145

feat: analyzer exceptions

---

wdl-analysis/CHANGELOG.md
wdl-analysis/src/analyzer.rs
wdl-analysis/src/handlers.rs
wdl-analysis/src/handlers/common.rs
wdl-analysis/src/handlers/common/docs.rs
wdl-analysis/src/handlers/common/position.rs
wdl-analysis/src/handlers/completions.rs
wdl-analysis/src/handlers/find_all_references.rs
wdl-analysis/src/handlers/goto_definition.rs
wdl-analysis/src/handlers/hover.rs
wdl-analysis/src/queue.rs
wdl-ast/CHANGELOG.md
wdl-ast/src/v1/workflow.rs
wdl-lsp/CHANGELOG.md
wdl-lsp/src/server.rs
wdl-lsp/tests/hover.rs
wdl-lsp/tests/workspace/hover/lib.wdl
wdl-lsp/tests/workspace/hover/meta.wdl
wdl-lsp/tests/workspace/hover/source.wdl

feat: add support for LSP hover

---

wdl-analysis/CHANGELOG.md
wdl-analysis/src/analyzer.rs
wdl-analysis/src/handlers.rs
wdl-analysis/src/handlers/goto_definition.rs
wdl-analysis/src/handlers/rename.rs
wdl-analysis/src/queue.rs
wdl-lsp/CHANGELOG.md
wdl-lsp/src/server.rs
wdl-lsp/tests/rename.rs
wdl-lsp/tests/workspace/rename/foo.wdl
wdl-lsp/tests/workspace/rename/source.wdl
wdl-lsp/tests/workspace/rename/structs.wdl

feat: add support for LSP renaming

---

wdl-analysis/CHANGELOG.md
wdl-analysis/src/analyzer.rs
wdl-analysis/src/handlers.rs
wdl-analysis/src/handlers/semantic_tokens.rs
wdl-analysis/src/queue.rs
wdl-grammar/CHANGELOG.md
wdl-grammar/src/tree.rs
wdl-lsp/CHANGELOG.md
wdl-lsp/src/server.rs

feat: add support for semantic highlighting

---

.gitattributes

see https://github.com/stjude-rust-labs/sprocket/pull/161
This repo isn't as bad, but I figure for consistency we might as well update here too.

chore: consider doc test files as vendored

---

.gitattributes

see https://github.com/stjude-rust-labs/sprocket/pull/163

fix: git attributes pattern matching

---

wdl-analysis/CHANGELOG.md
wdl-analysis/src/config.rs
wdl-analysis/src/handlers.rs
wdl-analysis/src/handlers/completions.rs
wdl-analysis/src/handlers/snippets.rs
wdl-lsp/CHANGELOG.md
wdl-lsp/src/server.rs
wdl-lsp/tests/completions.rs
wdl-lsp/tests/workspace/completions/snippet_local.wdl
wdl-lsp/tests/workspace/completions/snippet_ns.wdl
wdl-lsp/tests/workspace/completions/snippet_struct.wdl

feat: add snippets support

---

Cargo.toml
wdl-engine/src/backend/local.rs
wdl/CHANGELOG.md

chore: update Crankshaft dependency.
